[package]
name = "rust_program_design"
version = "0.1.0"
authors = ["KipleTsewell <tsewell.xie@greenpacket.com.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
